version: '3.9'
services:
  app:
    build: .
    ports:
      - '6000:6000'
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
    restart: always
